sms:
    menuitem_separator: '|'
    actions:
        leftclick:
            normal: execute
            sneak: none
        wheeldown:
            normal: none
            sneak: scrolldown
        wheelup:
            normal: none
            sneak: scrollup
        rightclick:
            normal: scrolldown
            sneak: scrollup
        spout:
            execute: key_return
            down: key_down
            up: key_up
    autosave: true
    no_explosions: true
    no_physics: true
    no_destroy_signs: true
    item_prefix:
        selected: '> '
        not_selected: '  '
    item_justify: left
    title_justify: center
    max_title_lines: 1
    ignore_view_ownership: true
    elevation:
        nodes: []
        grant_op: false
    inv_view:
        default_icon: stone
    maps:
        font: SansSerif
        show_tooltips: true
        break_block_id: 0
        transfer:
            to_sign: true
            from_sign: true
    spout:
        double_click: false
        list_alpha: 0.5
        list_background: ccc072
        show_tooltips: true
    redstonecontrol:
        execute: false
        scrollup: true
        scrolldown: true
    redstoneoutput:
        pulseticks: 20
    persistent_user_vars: false
    resource_base_url: ''
    log_commands: false
    command_log_file: ''
    log_level: INFO
    mcstats: true
    autocreate_views: true
    pager:
        lines: 0
    back_item:
        label: BACK
        material: 324