sms:
    menuitem_separator: '|'
    actions:
        leftclick:
            normal: execute
            sneak: none
        wheeldown:
            normal: scrolldown
            sneak: scrolldown
        wheelup:
            normal: scrollup
            sneak: scrollup
        rightclick:
            normal: scrolldown
            sneak: scrollup
        spout:
            execute: key_return
            down: key_down
            up: key_up
    autosave: true
    no_explosions: true
    no_physics: true
    no_destroy_signs: false
    item_prefix:
        selected: '> '
        not_selected: '  '
    item_justify: left
    ignore_view_ownership: true
    elevation:
        nodes: []
        grant_op: false
    spout:
        double_click: false
        show_command_text: true
    persistent_user_vars: false
    resource_base_url: ''
    log_commands: false
    command_log_file: ''
    