sms:
    actions:
        leftclick:
            normal: execute
            sneak: execute
        wheeldown:
            normal: scrolldown
            sneak: scrolldown
        wheelup:
            normal: scrollup
            sneak: scrollup
        rightclick:
            normal: scrolldown
            sneak: scrollup
        spout:
            execute: key_return
            down: key_down
            up: key_up
    no_explosions: true
    no_physics: true
    no_destroy_signs: true
    no_itemframe_damage: true
    item_prefix:
        selected: '> '
        not_selected: '  '
    item_justify: left
    title_justify: center
    max_title_lines: 1
    elevation:
        nodes: []
        grant_op: false
    inv_view:
        default_icon: stone
    maps:
        font: SansSerif
        fontsize: 9
        show_tooltips: true
        background: 9
        transfer:
            to_sign: true
            from_sign: true
    spout:
        double_click: false
        list_alpha: 0.5
        list_background: ccc072
        show_tooltips: true
    redstonecontrol:
        execute: false
        scrollup: true
        scrolldown: true
    redstoneoutput:
        pulseticks: 10
    resource_base_url: ''
    log_commands: false
    command_log_file: ''
    debug_level: 0
    mcstats: true
    autocreate_views: true
    pager:
        lines: 0
    submenus:
        back_item:
            label: '&l<- BACK'
            material: wood_door
        title_prefix: '->'
    coloured_console: true
    scroll_type: SCROLL
