name: ScrollingMenuSign
description: Scrollable command menus with signs/maps/spout/redstone views
author: desht
website: http://dev.bukkit.org/server-mods/scrollingmenusign
main: me.desht.scrollingmenusign.ScrollingMenuSign
version: 1.2.999
softdepend: [ Spout, Vault ]
commands:
  sms:
    description: Scrolling menu sign control
    usage: |
      /sms create <name> <title>
      /sms delete [<name>]
      /sms sync <name>
      /sms break
      /sms list [<name>]
      /sms show [<name>]
      /sms title <name> <new-title>
      /sms add <name> <label|command|message>
      /sms remove <name> <index|label>
      /sms sort <name> [auto]
      /sms uses <name> <item> <count>|clear [global]
      /sms page [<page-number|n|p>]
      /sms getcfg [<key>]
      /sms setcfg <key> <value>
      /sms macro <list|add|remove> <macro-name> ...
      /sms save [<all|menus|macros|config>]
      /sms reload [<all|menus|macros|config>]
      /sms defcmd <menu> <command>
      /sms givemap <map-id> <quantity> [<player>]
      /sms var [<name>] [<value>]
permissions:
  scrollingmenusign.guest:
    description: Gives access to very basic SMS functionality (no permission elevation)
    default: false
    children:
      scrollingmenusign.scroll: true
      scrollingmenusign.execute: true
      scrollingmenusign.execute.elevated: false
  scrollingmenusign.user:
    description: Gives access to basic SMS functionality
    default: true
    children:
      scrollingmenusign.scroll: true
      scrollingmenusign.execute: true
      scrollingmenusign.execute.elevated: true
  scrollingmenusign.poweruser:
    description: Gives access to basic SMS functionality plus map and spout views
    default: false
    children:
      scrollingmenusign.scroll: true
      scrollingmenusign.execute: true
      scrollingmenusign.execute.elevated: true
      scrollingmenusign.commands.getcfg: true
      scrollingmenusign.commands.list: true
      scrollingmenusign.commands.show: true
      scrollingmenusign.use.map: true
      scrollingmenusign.use.spout: true
  scrollingmenusign.admin:
    description: Gives complete access to all SMS features
    default: op
    children:
      scrollingmenusign.scroll: true
      scrollingmenusign.execute: true
      scrollingmenusign.execute.elevated: true
      scrollingmenusign.use.map: true
      scrollingmenusign.use.spout: true
      scrollingmenusign.commands.create: true
      scrollingmenusign.commands.title: true
      scrollingmenusign.commands.delete: true
      scrollingmenusign.commands.break: true
      scrollingmenusign.commands.sync: true
      scrollingmenusign.commands.add: true
      scrollingmenusign.commands.remove: true
      scrollingmenusign.commands.save: true
      scrollingmenusign.commands.reload: true
      scrollingmenusign.commands.macro: true
      scrollingmenusign.commands.getcfg: true
      scrollingmenusign.commands.setcfg: true
      scrollingmenusign.commands.list: true
      scrollingmenusign.commands.show: true
      scrollingmenusign.commands.debug: true
      scrollingmenusign.commands.sort: true
      scrollingmenusign.commands.defcmd: true
      scrollingmenusign.commands.givemap: true
      scrollingmenusign.commands.uses: true
      scrollingmenusign.commands.view: true
      scrollingmenusign.coloursigns: true
      scrollingmenusign.destroy: true
      scrollingmenusign.maps.toSign: true
      scrollingmenusign.maps.fromSign: true
      scrollingmenusign.create.elevated: true
      scrollingmenusign.create.cost: true
      scrollingmenusign.create.redstonecontrol: true
      scrollingmenusign.create.switch: true
      scrollingmenusign.ignoreViewOwnership: true
  scrollingmenusign.commands.create:
    description: Allow creation of new menus
    default: op
  scrollingmenusign.commands.title:
    description: Allow the title of menus to be changed
    default: op
  scrollingmenusign.commands.delete:
    description: Allow deletion of menus
    default: op
  scrollingmenusign.commands.break:
    description: Allows signs to be removed from menus
    default: op
  scrollingmenusign.commands.sync:
    description: Allows signs to be added to (synchronised with) menus
    default: op
  scrollingmenusign.commands.add:
    description: Allows menu items to be added to a menu
    default: op
  scrollingmenusign.commands.remove:
    description: Allows menu items to be removed from a menu
    default: op
  scrollingmenusign.commands.save:
    description: Allows saving of persisted data
    default: op
  scrollingmenusign.commands.reload:
    description: Allows reloading of persisted data
    default: op
  scrollingmenusign.commands.macro:
    description: Allows usage of macro management commands
    default: op
  scrollingmenusign.commands.debug:
    description: Allows debugging of the plugin
    default: op
  scrollingmenusign.commands.sort:
    description: Allows menus to be sorted
    default: op
  scrollingmenusign.commands.uses:
    description: Allows the permitted use count of a menu item to be set
    default: op
  scrollingmenusign.commands.getcfg:
    description: Allows configuration items to be viewed
    default: op
  scrollingmenusign.commands.setcfg:
    description: Allows configuration items to be changed
    default: op
  scrollingmenusign.commands.givemap:
    description: Allows giving of maps with a specific map ID
    default: op
  scrollingmenusign.destroy:
    description: Allows destruction of views belonging to a menu created by someone else
    default: op
  scrollingmenusign.coloursigns:
    description: Allows creation of signs with coloured titles and menu items
    default: op
  scrollingmenusign.colorsigns:
    description: Synonym for scrollingmenusign.coloursigns
    default: op
  scrollingmenusign.commands.list:
    description: Allows menus to be listed
    default: op
  scrollingmenusign.commands.show:
    description: Allows menu contents to be shown
    default: op
  scrollingmenusign.commands.view:
    description: Allows menu views to be inspected and modified
    default: op
  scrollingmenusign.commands.var:
    description: Allows command substitution variables to be defined
    default: true
  scrollingmenusign.scroll:
    description: Allows menus to be scrolled
    default: true
  scrollingmenusign.execute:
    description: Allows menu items to be executed
    default: true
  scrollingmenusign.create.elevated:
    description: Allows creation of menu items which bypass permissions checks
    default: op
  scrollingmenusign.commands.page:
    description: Allows output data to be paged
    default: true
  scrollingmenusign.maps.fromSign:
    description: Allows map views to be copied from sign views
    default: op
  scrollingmenusign.maps.toSign:
    description: Allows map views to be copied to sign views
    default: op
  scrollingmenusign.create.cost:
    description: Allows creation of menu items which have a cost
    default: op
  scrollingmenusign.execute.elevated:
    description: Allow execution of menu items which bypass permissions checks
    default: true
  scrollingmenusign.ignoreViewOwnership:
    description: Allows views owned by others to be used (overrides sms.use_any_view config setting)
    default: op
  scrollingmenusign.use.map:
    description: Allows usage of map views
    default: op
  scrollingmenusign.use.spout:
    description: Allows usage of Spout views
    default: op
  scrollingmenusign.use.sign:
    description: Allows usage of sign views
    default: true
  scrollingmenusign.use.redstone:
    description: Allows usage of redstone views
    default: true
  scrollingmenusign.create.redstonecontrol:
    description: Allows creation of redstone control signs
    default: op
  scrollingmenusign.create.switch:
    description: Allows creation of redstone output switches
    default: op
