name: ScrollingMenuSign
description: Scrollable command menus with multiple view types
author: desht
website: http://dev.bukkit.org/server-mods/scrollingmenusign
main: me.desht.scrollingmenusign.ScrollingMenuSign
version: ${project.version}
softdepend: [ Spout, Vault ]
commands:
  sms:
    description: ScrollingMenuSign management
    usage: |
      /sms create <menu-name> <title>
      /sms delete [<menu-name>]
      /sms undelete <menu-name>
      /sms list [<menu-name>]
      /sms menu <menu-name> <options...>
      /sms add <menu-name> <label> <command> <options...>
      /sms remove <menu-name> <@index>|<label>
      /sms edit <menu-name> <@index>|<label> <options...>
      /sms uses <menu-name> [<item>] <count>|clear [-global]
      /sms sync <menu-name> <options...>
      /sms break <options...>
      /sms view <view-name> <options...>
      /sms getcfg [<key>]
      /sms setcfg <key> <value>
      /sms macro <list|add|remove> <macro-name> ...
      /sms save [<all|menus|macros|config>]
      /sms reload [<all|menus|macros|config>]
      /sms give map <map-id> <quantity> [<player>]
      /sms give book <view-name> <quantity> [<player>]
      /sms var [<var-name>] [<value>]
      /sms page [<page-number|n|p>]
permissions:
  scrollingmenusign.guest:
    description: Gives access to very basic SMS functionality (no permission elevation)
    default: false
    children:
      scrollingmenusign.scroll: true
      scrollingmenusign.execute: true
      scrollingmenusign.execute.elevated: false
  scrollingmenusign.user:
    description: Gives access to basic SMS functionality
    default: true
    children:
      scrollingmenusign.scroll: true
      scrollingmenusign.execute: true
      scrollingmenusign.execute.elevated: true
  scrollingmenusign.poweruser:
    description: Gives access to basic SMS functionality plus map/spout/inventory views
    default: false
    children:
      scrollingmenusign.scroll: true
      scrollingmenusign.execute: true
      scrollingmenusign.execute.elevated: true
      scrollingmenusign.commands.getcfg: true
      scrollingmenusign.commands.list: true
      scrollingmenusign.commands.show: true
      scrollingmenusign.use.map: true
      scrollingmenusign.use.inventory: true
      scrollingmenusign.use.spout: true
  scrollingmenusign.limited_admin:
    description: Gives limited administration rights for SMS
    default: false
    children:
      scrollingmenusign.scroll: true
      scrollingmenusign.execute: true
      scrollingmenusign.execute.elevated: true
      scrollingmenusign.use.map: true
      scrollingmenusign.use.inventory: true
      scrollingmenusign.use.spout: true
      scrollingmenusign.commands.create: true
      scrollingmenusign.commands.delete: true
      scrollingmenusign.commands.undelete: true
      scrollingmenusign.commands.break: true
      scrollingmenusign.commands.sync: true
      scrollingmenusign.commands.add: true
      scrollingmenusign.commands.remove: true
      scrollingmenusign.commands.macro: true
      scrollingmenusign.commands.getcfg: true
      scrollingmenusign.commands.list: true
      scrollingmenusign.commands.uses: true
      scrollingmenusign.commands.view: true
      scrollingmenusign.commands.var: true
      scrollingmenusign.commands.edit: true
      scrollingmenusign.commands.font: true
      scrollingmenusign.commands.menu: true
      scrollingmenusign.coloursigns: true
      scrollingmenusign.maps.to.sign: true
      scrollingmenusign.maps.from.sign: true
      scrollingmenusign.create.switch: true
  scrollingmenusign.admin:
    description: Gives complete access to all SMS features
    default: op
    children:
      scrollingmenusign.scroll: true
      scrollingmenusign.execute: true
      scrollingmenusign.execute.elevated: true
      scrollingmenusign.use.map: true
      scrollingmenusign.use.inventory: true
      scrollingmenusign.use.spout: true
      scrollingmenusign.commands.create: true
      scrollingmenusign.commands.delete: true
      scrollingmenusign.commands.undelete: true
      scrollingmenusign.commands.break: true
      scrollingmenusign.commands.sync: true
      scrollingmenusign.commands.add: true
      scrollingmenusign.commands.remove: true
      scrollingmenusign.commands.save: true
      scrollingmenusign.commands.reload: true
      scrollingmenusign.commands.macro: true
      scrollingmenusign.commands.getcfg: true
      scrollingmenusign.commands.setcfg: true
      scrollingmenusign.commands.list: true
      scrollingmenusign.commands.sort: true
      scrollingmenusign.commands.give: true
      scrollingmenusign.commands.uses: true
      scrollingmenusign.commands.view: true
      scrollingmenusign.commands.var: true
      scrollingmenusign.commands.edit: true
      scrollingmenusign.commands.font: true
      scrollingmenusign.commands.menu: true
      scrollingmenusign.coloursigns: true
      scrollingmenusign.destroy: true
      scrollingmenusign.maps.t.sign: true
      scrollingmenusign.maps.from.sign: true
      scrollingmenusign.create.elevated: true
      scrollingmenusign.create.cost: true
      scrollingmenusign.create.redstonecontrol: true
      scrollingmenusign.create.switch: true
      scrollingmenusign.access.any: true
      scrollingmenusign.edit.any: true
      scrollingmenusign.vars.other: true
  scrollingmenusign.commands.create:
    description: Allow creation of new menus
    default: op
  scrollingmenusign.commands.delete:
    description: Allow deletion of menus
    default: op
  scrollingmenusign.commands.break:
    description: Allows views to be removed from menus
    default: op
  scrollingmenusign.commands.sync:
    description: Allows views to be added to (synchronised with) menus
    default: op
  scrollingmenusign.commands.add:
    description: Allows new menu items to be added to a menu
    default: op
  scrollingmenusign.commands.remove:
    description: Allows menu items to be removed from a menu
    default: op
  scrollingmenusign.commands.save:
    description: Allows saving of persisted data
    default: op
  scrollingmenusign.commands.reload:
    description: Allows reloading of persisted data
    default: op
  scrollingmenusign.commands.macro:
    description: Allows usage of macro management commands
    default: op
  scrollingmenusign.commands.uses:
    description: Allows the permitted use count of a menu item to be set
    default: op
  scrollingmenusign.commands.getcfg:
    description: Allows configuration items to be viewed
    default: op
  scrollingmenusign.commands.setcfg:
    description: Allows configuration items to be changed
    default: op
  scrollingmenusign.commands.give:
    description: Allows giving of map or book items to self or others
    default: op
  scrollingmenusign.commands.list:
    description: Allows menus, and the views for a menu, to be listed
    default: op
  scrollingmenusign.commands.show:
    description: Allows menu contents to be shown
    default: op
  scrollingmenusign.commands.view:
    description: Allows view attributes to be inspected and modified
    default: op
  scrollingmenusign.commands.var:
    description: Allows command substitution variables to be defined
    default: op
  scrollingmenusign.commands.edit:
    description: Allows menu items to be edited in existing menus
    default: op
  scrollingmenusign.commands.font:
    description: Allows listing of fonts known to the system (for use in map views)
    default: op
  scrollingmenusign.commands.menu:
    description: Allows menu attributes to be inspected and modified
    default: op
  scrollingmenusign.commands.page:
    description: Allows output data to be paged
    default: true
  scrollingmenusign.commands.undelete:
    description: Allows restoration of deleted menus
    default: op
  scrollingmenusign.destroy:
    description: Allows destruction of views belonging to a menu created by someone else
    default: op
  scrollingmenusign.coloursigns:
    description: Allows creation of signs with coloured titles and menu items
    default: op
  scrollingmenusign.colorsigns:
    description: Synonym for scrollingmenusign.coloursigns
    default: op
  scrollingmenusign.scroll:
    description: Allows menus to be scrolled
    default: true
  scrollingmenusign.execute:
    description: Allows menu items to be executed
    default: true
  scrollingmenusign.maps.from.sign:
    description: Allows map views to be copied from sign views
    default: op
  scrollingmenusign.maps.to.sign:
    description: Allows map views to be copied to sign views
    default: op
  scrollingmenusign.create.cost:
    description: Allows creation of menu items which have a cost
    default: op
  scrollingmenusign.create.elevated:
    description: Allows creation of menu items which bypass permissions checks
    default: op
  scrollingmenusign.execute.elevated:
    description: Allow execution of menu items which bypass permissions checks
    default: true
  scrollingmenusign.access.any:
    description: Allows use of any menu or view, overriding the menu or view's access controls
    default: op
  scrollingmenusign.edit.any:
    description: Allows modification of any menu or view, regardless of ownership
    default: op
  scrollingmenusign.use.map:
    description: Allows usage of map views
    default: op
  scrollingmenusign.use.sign:
    description: Allows usage of sign views
    default: true
  scrollingmenusign.use.multisign:
    description: Allows usage of multisign views
    default: true
  scrollingmenusign.use.redstone:
    description: Allows usage of redstone views
    default: true
  scrollingmenusign.use.inventory:
    description: Allows usage of inventory views
    default: op
  scrollingmenusign.use.spout:
    description: Allows usage of Spout views
    default: op
  scrollingmenusign.create.redstonecontrol:
    description: Allows creation of redstone control signs
    default: op
  scrollingmenusign.create.switch:
    description: Allows creation of redstone output switches
    default: op
  scrollingmenusign.vars.other:
    description: Allows get/set/delete of variables belonging to other users with "/sms var"
    default: op
