name: ScrollingMenuSign
main: me.desht.scrollingmenusign.ScrollingMenuSign
version: 0.3
softdepend: [ Permissions, CommandSigns ]
commands:
  sms:
    description: Scrolling menu sign control
    usage: |
      /sms create <name> <title>
      /sms create <name> from <other-name>
      /sms sync <name>
      /sms delete [<name>]
      /sms break
      /sms list
      /sms show [<name>]
      /sms title <name> <new-title>
      /sms add <name> <label|command|message>
      /sms remove <name> <index>
      /sms page <page-number>
      /sms getcfg [<key>]
      /sms setcfg <key> <value>
      /sms macro <list|add|remove> <macro-name> ...
      /sms save
      /sms reload
      