name: ScrollingMenuSign
main: me.desht.scrollingmenusign.ScrollingMenuSign
version: 0.2
commands:
  sms:
    description: Scrolling menu sign control
    usage: |
      /sms create <name> <title>
      /sms create <name> from <other-name>
      /sms break [<name>]
      /sms list
      /sms show [<name>]
      /sms title <name> <new-title>
      /sms add <name> <label|command|message>
      /sms remove <name> <index>
      /sms page <page-number>
      /sms getcfg [<key>]
      /sms setcfg <key> <value>
      /sms save
      /sms reload
      